sudo: required
services:
  - docker

before_install:
  - docker build -t alexiastandish/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexiastandish/react-test npm test

after_success:
  - docker build -t alexiastandish/multi-client ./client
  - docker build -t alexiastandish/multi-nginx ./nginx
  - docker build -t alexiastandish/multi-server ./server
  - docker build -t alexiastandish/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push alexiastandish/multi-client
  - docker push alexiastandish/multi-nginx
  - docker push alexiastandish/multi-server
  - docker push alexiastandish/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi'
  env: 'Multi-env'
  bucket_name: 'elasticbeanstalk-us-east-2-360235357203'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
